//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppIntegracaoCECTiny.CeCService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Pedido[] pedidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string erroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AppIntegracaoCECTiny.CeCService.Pedido[] pedidos {
            get {
                return this.pedidosField;
            }
            set {
                if ((object.ReferenceEquals(this.pedidosField, value) != true)) {
                    this.pedidosField = value;
                    this.RaisePropertyChanged("pedidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string erro {
            get {
                return this.erroField;
            }
            set {
                if ((object.ReferenceEquals(this.erroField, value) != true)) {
                    this.erroField = value;
                    this.RaisePropertyChanged("erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.mensagemField, value) != true)) {
                    this.mensagemField = value;
                    this.RaisePropertyChanged("mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Header headerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Item[] itensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AppIntegracaoCECTiny.CeCService.Header header {
            get {
                return this.headerField;
            }
            set {
                if ((object.ReferenceEquals(this.headerField, value) != true)) {
                    this.headerField = value;
                    this.RaisePropertyChanged("header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AppIntegracaoCECTiny.CeCService.Item[] itens {
            get {
                return this.itensField;
            }
            set {
                if ((object.ReferenceEquals(this.itensField, value) != true)) {
                    this.itensField = value;
                    this.RaisePropertyChanged("itens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Fornecedor fornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Cliente clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Filial filialpedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Filial filialentregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Filial filialfaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Filial filialcobrancaField;
        
        private int numpedidoField;
        
        private System.DateTime dataemissaoField;
        
        private decimal valorpedidoField;
        
        private System.DateTime dataentregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string precofirmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string possuiipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string obsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string condpagtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dscondpagtoField;
        
        private decimal pdescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descdescontoField;
        
        private int prazoparcelaField;
        
        private int proporcaoField;
        
        private int pcparcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tppagtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string livredebitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tppedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpcobrancaField;
        
        private decimal totpedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recmercadoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string possuifreteField;
        
        private decimal vlfreteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpfreteField;
        
        private decimal numpedidoantigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string canceladoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emitidoporField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailemissorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AppIntegracaoCECTiny.CeCService.Fornecedor fornecedor {
            get {
                return this.fornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.fornecedorField, value) != true)) {
                    this.fornecedorField = value;
                    this.RaisePropertyChanged("fornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppIntegracaoCECTiny.CeCService.Cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.clienteField, value) != true)) {
                    this.clienteField = value;
                    this.RaisePropertyChanged("cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AppIntegracaoCECTiny.CeCService.Filial filialpedido {
            get {
                return this.filialpedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.filialpedidoField, value) != true)) {
                    this.filialpedidoField = value;
                    this.RaisePropertyChanged("filialpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AppIntegracaoCECTiny.CeCService.Filial filialentrega {
            get {
                return this.filialentregaField;
            }
            set {
                if ((object.ReferenceEquals(this.filialentregaField, value) != true)) {
                    this.filialentregaField = value;
                    this.RaisePropertyChanged("filialentrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AppIntegracaoCECTiny.CeCService.Filial filialfatura {
            get {
                return this.filialfaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.filialfaturaField, value) != true)) {
                    this.filialfaturaField = value;
                    this.RaisePropertyChanged("filialfatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public AppIntegracaoCECTiny.CeCService.Filial filialcobranca {
            get {
                return this.filialcobrancaField;
            }
            set {
                if ((object.ReferenceEquals(this.filialcobrancaField, value) != true)) {
                    this.filialcobrancaField = value;
                    this.RaisePropertyChanged("filialcobranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int numpedido {
            get {
                return this.numpedidoField;
            }
            set {
                if ((this.numpedidoField.Equals(value) != true)) {
                    this.numpedidoField = value;
                    this.RaisePropertyChanged("numpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime dataemissao {
            get {
                return this.dataemissaoField;
            }
            set {
                if ((this.dataemissaoField.Equals(value) != true)) {
                    this.dataemissaoField = value;
                    this.RaisePropertyChanged("dataemissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal valorpedido {
            get {
                return this.valorpedidoField;
            }
            set {
                if ((this.valorpedidoField.Equals(value) != true)) {
                    this.valorpedidoField = value;
                    this.RaisePropertyChanged("valorpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime dataentrega {
            get {
                return this.dataentregaField;
            }
            set {
                if ((this.dataentregaField.Equals(value) != true)) {
                    this.dataentregaField = value;
                    this.RaisePropertyChanged("dataentrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string precofirme {
            get {
                return this.precofirmeField;
            }
            set {
                if ((object.ReferenceEquals(this.precofirmeField, value) != true)) {
                    this.precofirmeField = value;
                    this.RaisePropertyChanged("precofirme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string possuiipi {
            get {
                return this.possuiipiField;
            }
            set {
                if ((object.ReferenceEquals(this.possuiipiField, value) != true)) {
                    this.possuiipiField = value;
                    this.RaisePropertyChanged("possuiipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string obs {
            get {
                return this.obsField;
            }
            set {
                if ((object.ReferenceEquals(this.obsField, value) != true)) {
                    this.obsField = value;
                    this.RaisePropertyChanged("obs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string condpagto {
            get {
                return this.condpagtoField;
            }
            set {
                if ((object.ReferenceEquals(this.condpagtoField, value) != true)) {
                    this.condpagtoField = value;
                    this.RaisePropertyChanged("condpagto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string dscondpagto {
            get {
                return this.dscondpagtoField;
            }
            set {
                if ((object.ReferenceEquals(this.dscondpagtoField, value) != true)) {
                    this.dscondpagtoField = value;
                    this.RaisePropertyChanged("dscondpagto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public decimal pdesconto {
            get {
                return this.pdescontoField;
            }
            set {
                if ((this.pdescontoField.Equals(value) != true)) {
                    this.pdescontoField = value;
                    this.RaisePropertyChanged("pdesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string descdesconto {
            get {
                return this.descdescontoField;
            }
            set {
                if ((object.ReferenceEquals(this.descdescontoField, value) != true)) {
                    this.descdescontoField = value;
                    this.RaisePropertyChanged("descdesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int prazoparcela {
            get {
                return this.prazoparcelaField;
            }
            set {
                if ((this.prazoparcelaField.Equals(value) != true)) {
                    this.prazoparcelaField = value;
                    this.RaisePropertyChanged("prazoparcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int proporcao {
            get {
                return this.proporcaoField;
            }
            set {
                if ((this.proporcaoField.Equals(value) != true)) {
                    this.proporcaoField = value;
                    this.RaisePropertyChanged("proporcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int pcparcela {
            get {
                return this.pcparcelaField;
            }
            set {
                if ((this.pcparcelaField.Equals(value) != true)) {
                    this.pcparcelaField = value;
                    this.RaisePropertyChanged("pcparcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string tppagto {
            get {
                return this.tppagtoField;
            }
            set {
                if ((object.ReferenceEquals(this.tppagtoField, value) != true)) {
                    this.tppagtoField = value;
                    this.RaisePropertyChanged("tppagto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string livredebito {
            get {
                return this.livredebitoField;
            }
            set {
                if ((object.ReferenceEquals(this.livredebitoField, value) != true)) {
                    this.livredebitoField = value;
                    this.RaisePropertyChanged("livredebito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string tppedido {
            get {
                return this.tppedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.tppedidoField, value) != true)) {
                    this.tppedidoField = value;
                    this.RaisePropertyChanged("tppedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string tpcobranca {
            get {
                return this.tpcobrancaField;
            }
            set {
                if ((object.ReferenceEquals(this.tpcobrancaField, value) != true)) {
                    this.tpcobrancaField = value;
                    this.RaisePropertyChanged("tpcobranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public decimal totpedido {
            get {
                return this.totpedidoField;
            }
            set {
                if ((this.totpedidoField.Equals(value) != true)) {
                    this.totpedidoField = value;
                    this.RaisePropertyChanged("totpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string recmercadoria {
            get {
                return this.recmercadoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.recmercadoriaField, value) != true)) {
                    this.recmercadoriaField = value;
                    this.RaisePropertyChanged("recmercadoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string possuifrete {
            get {
                return this.possuifreteField;
            }
            set {
                if ((object.ReferenceEquals(this.possuifreteField, value) != true)) {
                    this.possuifreteField = value;
                    this.RaisePropertyChanged("possuifrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public decimal vlfrete {
            get {
                return this.vlfreteField;
            }
            set {
                if ((this.vlfreteField.Equals(value) != true)) {
                    this.vlfreteField = value;
                    this.RaisePropertyChanged("vlfrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string tpfrete {
            get {
                return this.tpfreteField;
            }
            set {
                if ((object.ReferenceEquals(this.tpfreteField, value) != true)) {
                    this.tpfreteField = value;
                    this.RaisePropertyChanged("tpfrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public decimal numpedidoantigo {
            get {
                return this.numpedidoantigoField;
            }
            set {
                if ((this.numpedidoantigoField.Equals(value) != true)) {
                    this.numpedidoantigoField = value;
                    this.RaisePropertyChanged("numpedidoantigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string cancelado {
            get {
                return this.canceladoField;
            }
            set {
                if ((object.ReferenceEquals(this.canceladoField, value) != true)) {
                    this.canceladoField = value;
                    this.RaisePropertyChanged("cancelado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string emitidopor {
            get {
                return this.emitidoporField;
            }
            set {
                if ((object.ReferenceEquals(this.emitidoporField, value) != true)) {
                    this.emitidoporField = value;
                    this.RaisePropertyChanged("emitidopor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string emailemissor {
            get {
                return this.emailemissorField;
            }
            set {
                if ((object.ReferenceEquals(this.emailemissorField, value) != true)) {
                    this.emailemissorField = value;
                    this.RaisePropertyChanged("emailemissor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codbarraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codproddfField;
        
        private decimal qtdeField;
        
        private decimal precounitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unidmaiorField;
        
        private decimal vlipiField;
        
        private decimal aliqipiField;
        
        private decimal vltotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codbarra {
            get {
                return this.codbarraField;
            }
            set {
                if ((object.ReferenceEquals(this.codbarraField, value) != true)) {
                    this.codbarraField = value;
                    this.RaisePropertyChanged("codbarra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string codproddf {
            get {
                return this.codproddfField;
            }
            set {
                if ((object.ReferenceEquals(this.codproddfField, value) != true)) {
                    this.codproddfField = value;
                    this.RaisePropertyChanged("codproddf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal qtde {
            get {
                return this.qtdeField;
            }
            set {
                if ((this.qtdeField.Equals(value) != true)) {
                    this.qtdeField = value;
                    this.RaisePropertyChanged("qtde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal precounit {
            get {
                return this.precounitField;
            }
            set {
                if ((this.precounitField.Equals(value) != true)) {
                    this.precounitField = value;
                    this.RaisePropertyChanged("precounit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string unidmaior {
            get {
                return this.unidmaiorField;
            }
            set {
                if ((object.ReferenceEquals(this.unidmaiorField, value) != true)) {
                    this.unidmaiorField = value;
                    this.RaisePropertyChanged("unidmaior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal vlipi {
            get {
                return this.vlipiField;
            }
            set {
                if ((this.vlipiField.Equals(value) != true)) {
                    this.vlipiField = value;
                    this.RaisePropertyChanged("vlipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal aliqipi {
            get {
                return this.aliqipiField;
            }
            set {
                if ((this.aliqipiField.Equals(value) != true)) {
                    this.aliqipiField = value;
                    this.RaisePropertyChanged("aliqipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal vltotal {
            get {
                return this.vltotalField;
            }
            set {
                if ((this.vltotalField.Equals(value) != true)) {
                    this.vltotalField = value;
                    this.RaisePropertyChanged("vltotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fornecedor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Fornecedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codforneintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razsocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Endereco enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tpinscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cgccpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string representanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codforneint {
            get {
                return this.codforneintField;
            }
            set {
                if ((object.ReferenceEquals(this.codforneintField, value) != true)) {
                    this.codforneintField = value;
                    this.RaisePropertyChanged("codforneint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string razsoc {
            get {
                return this.razsocField;
            }
            set {
                if ((object.ReferenceEquals(this.razsocField, value) != true)) {
                    this.razsocField = value;
                    this.RaisePropertyChanged("razsoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AppIntegracaoCECTiny.CeCService.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tpinsc {
            get {
                return this.tpinscField;
            }
            set {
                if ((object.ReferenceEquals(this.tpinscField, value) != true)) {
                    this.tpinscField = value;
                    this.RaisePropertyChanged("tpinsc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cgccpf {
            get {
                return this.cgccpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cgccpfField, value) != true)) {
                    this.cgccpfField = value;
                    this.RaisePropertyChanged("cgccpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string fone {
            get {
                return this.foneField;
            }
            set {
                if ((object.ReferenceEquals(this.foneField, value) != true)) {
                    this.foneField = value;
                    this.RaisePropertyChanged("fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                if ((object.ReferenceEquals(this.faxField, value) != true)) {
                    this.faxField = value;
                    this.RaisePropertyChanged("fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string representante {
            get {
                return this.representanteField;
            }
            set {
                if ((object.ReferenceEquals(this.representanteField, value) != true)) {
                    this.representanteField = value;
                    this.RaisePropertyChanged("representante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Endereco enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foneField;
        
        private decimal vendedorField;
        
        private decimal lojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cgccpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numdocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AppIntegracaoCECTiny.CeCService.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fone {
            get {
                return this.foneField;
            }
            set {
                if ((object.ReferenceEquals(this.foneField, value) != true)) {
                    this.foneField = value;
                    this.RaisePropertyChanged("fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal vendedor {
            get {
                return this.vendedorField;
            }
            set {
                if ((this.vendedorField.Equals(value) != true)) {
                    this.vendedorField = value;
                    this.RaisePropertyChanged("vendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal loja {
            get {
                return this.lojaField;
            }
            set {
                if ((this.lojaField.Equals(value) != true)) {
                    this.lojaField = value;
                    this.RaisePropertyChanged("loja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cgccpf {
            get {
                return this.cgccpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cgccpfField, value) != true)) {
                    this.cgccpfField = value;
                    this.RaisePropertyChanged("cgccpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string numdoc {
            get {
                return this.numdocField;
            }
            set {
                if ((object.ReferenceEquals(this.numdocField, value) != true)) {
                    this.numdocField = value;
                    this.RaisePropertyChanged("numdoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filial", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Filial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cgccpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppIntegracaoCECTiny.CeCService.Endereco enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faxField;
        
        private decimal codfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codfilvikamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomelojaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cgccpf {
            get {
                return this.cgccpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cgccpfField, value) != true)) {
                    this.cgccpfField = value;
                    this.RaisePropertyChanged("cgccpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ie {
            get {
                return this.ieField;
            }
            set {
                if ((object.ReferenceEquals(this.ieField, value) != true)) {
                    this.ieField = value;
                    this.RaisePropertyChanged("ie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AppIntegracaoCECTiny.CeCService.Endereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fone {
            get {
                return this.foneField;
            }
            set {
                if ((object.ReferenceEquals(this.foneField, value) != true)) {
                    this.foneField = value;
                    this.RaisePropertyChanged("fone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                if ((object.ReferenceEquals(this.faxField, value) != true)) {
                    this.faxField = value;
                    this.RaisePropertyChanged("fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal codfil {
            get {
                return this.codfilField;
            }
            set {
                if ((this.codfilField.Equals(value) != true)) {
                    this.codfilField = value;
                    this.RaisePropertyChanged("codfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string codfilvikam {
            get {
                return this.codfilvikamField;
            }
            set {
                if ((object.ReferenceEquals(this.codfilvikamField, value) != true)) {
                    this.codfilvikamField = value;
                    this.RaisePropertyChanged("codfilvikam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nomeloja {
            get {
                return this.nomelojaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomelojaField, value) != true)) {
                    this.nomelojaField = value;
                    this.RaisePropertyChanged("nomeloja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ufField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ender {
            get {
                return this.enderField;
            }
            set {
                if ((object.ReferenceEquals(this.enderField, value) != true)) {
                    this.enderField = value;
                    this.RaisePropertyChanged("ender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string municipio {
            get {
                return this.municipioField;
            }
            set {
                if ((object.ReferenceEquals(this.municipioField, value) != true)) {
                    this.municipioField = value;
                    this.RaisePropertyChanged("municipio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                if ((object.ReferenceEquals(this.cepField, value) != true)) {
                    this.cepField = value;
                    this.RaisePropertyChanged("cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uf {
            get {
                return this.ufField;
            }
            set {
                if ((object.ReferenceEquals(this.ufField, value) != true)) {
                    this.ufField = value;
                    this.RaisePropertyChanged("uf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.referenciaField, value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CeCService.PedidoCompraFornecedoresSoap")]
    public interface PedidoCompraFornecedoresSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento Login no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPedidosNaoVisualizados", ReplyAction="*")]
        AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse ListarPedidosNaoVisualizados(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarPedidosNaoVisualizados", ReplyAction="*")]
        System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse> ListarPedidosNaoVisualizadosAsync(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento Login no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmarRecebimentoPedido", ReplyAction="*")]
        AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse ConfirmarRecebimentoPedido(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmarRecebimentoPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse> ConfirmarRecebimentoPedidoAsync(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPedidosNaoVisualizadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPedidosNaoVisualizados", Namespace="http://tempuri.org/", Order=0)]
        public AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequestBody Body;
        
        public ListarPedidosNaoVisualizadosRequest() {
        }
        
        public ListarPedidosNaoVisualizadosRequest(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPedidosNaoVisualizadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Senha;
        
        public ListarPedidosNaoVisualizadosRequestBody() {
        }
        
        public ListarPedidosNaoVisualizadosRequestBody(string Login, string Senha) {
            this.Login = Login;
            this.Senha = Senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarPedidosNaoVisualizadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarPedidosNaoVisualizadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponseBody Body;
        
        public ListarPedidosNaoVisualizadosResponse() {
        }
        
        public ListarPedidosNaoVisualizadosResponse(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarPedidosNaoVisualizadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppIntegracaoCECTiny.CeCService.Response ListarPedidosNaoVisualizadosResult;
        
        public ListarPedidosNaoVisualizadosResponseBody() {
        }
        
        public ListarPedidosNaoVisualizadosResponseBody(AppIntegracaoCECTiny.CeCService.Response ListarPedidosNaoVisualizadosResult) {
            this.ListarPedidosNaoVisualizadosResult = ListarPedidosNaoVisualizadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmarRecebimentoPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmarRecebimentoPedido", Namespace="http://tempuri.org/", Order=0)]
        public AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequestBody Body;
        
        public ConfirmarRecebimentoPedidoRequest() {
        }
        
        public ConfirmarRecebimentoPedidoRequest(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmarRecebimentoPedidoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal CodigoPedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool SincronizarPedido;
        
        public ConfirmarRecebimentoPedidoRequestBody() {
        }
        
        public ConfirmarRecebimentoPedidoRequestBody(string Login, string Senha, decimal CodigoPedido, bool SincronizarPedido) {
            this.Login = Login;
            this.Senha = Senha;
            this.CodigoPedido = CodigoPedido;
            this.SincronizarPedido = SincronizarPedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmarRecebimentoPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmarRecebimentoPedidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponseBody Body;
        
        public ConfirmarRecebimentoPedidoResponse() {
        }
        
        public ConfirmarRecebimentoPedidoResponse(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConfirmarRecebimentoPedidoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppIntegracaoCECTiny.CeCService.Response ConfirmarRecebimentoPedidoResult;
        
        public ConfirmarRecebimentoPedidoResponseBody() {
        }
        
        public ConfirmarRecebimentoPedidoResponseBody(AppIntegracaoCECTiny.CeCService.Response ConfirmarRecebimentoPedidoResult) {
            this.ConfirmarRecebimentoPedidoResult = ConfirmarRecebimentoPedidoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoCompraFornecedoresSoapChannel : AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoCompraFornecedoresSoapClient : System.ServiceModel.ClientBase<AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap>, AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap {
        
        public PedidoCompraFornecedoresSoapClient() {
        }
        
        public PedidoCompraFornecedoresSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoCompraFornecedoresSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoCompraFornecedoresSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoCompraFornecedoresSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap.ListarPedidosNaoVisualizados(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest request) {
            return base.Channel.ListarPedidosNaoVisualizados(request);
        }
        
        public AppIntegracaoCECTiny.CeCService.Response ListarPedidosNaoVisualizados(string Login, string Senha) {
            AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest inValue = new AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest();
            inValue.Body = new AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Senha = Senha;
            AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse retVal = ((AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap)(this)).ListarPedidosNaoVisualizados(inValue);
            return retVal.Body.ListarPedidosNaoVisualizadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse> AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap.ListarPedidosNaoVisualizadosAsync(AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest request) {
            return base.Channel.ListarPedidosNaoVisualizadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosResponse> ListarPedidosNaoVisualizadosAsync(string Login, string Senha) {
            AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest inValue = new AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequest();
            inValue.Body = new AppIntegracaoCECTiny.CeCService.ListarPedidosNaoVisualizadosRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Senha = Senha;
            return ((AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap)(this)).ListarPedidosNaoVisualizadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap.ConfirmarRecebimentoPedido(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest request) {
            return base.Channel.ConfirmarRecebimentoPedido(request);
        }
        
        public AppIntegracaoCECTiny.CeCService.Response ConfirmarRecebimentoPedido(string Login, string Senha, decimal CodigoPedido, bool SincronizarPedido) {
            AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest inValue = new AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest();
            inValue.Body = new AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Senha = Senha;
            inValue.Body.CodigoPedido = CodigoPedido;
            inValue.Body.SincronizarPedido = SincronizarPedido;
            AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse retVal = ((AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap)(this)).ConfirmarRecebimentoPedido(inValue);
            return retVal.Body.ConfirmarRecebimentoPedidoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse> AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap.ConfirmarRecebimentoPedidoAsync(AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest request) {
            return base.Channel.ConfirmarRecebimentoPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoResponse> ConfirmarRecebimentoPedidoAsync(string Login, string Senha, decimal CodigoPedido, bool SincronizarPedido) {
            AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest inValue = new AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequest();
            inValue.Body = new AppIntegracaoCECTiny.CeCService.ConfirmarRecebimentoPedidoRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Senha = Senha;
            inValue.Body.CodigoPedido = CodigoPedido;
            inValue.Body.SincronizarPedido = SincronizarPedido;
            return ((AppIntegracaoCECTiny.CeCService.PedidoCompraFornecedoresSoap)(this)).ConfirmarRecebimentoPedidoAsync(inValue);
        }
    }
}
